---
#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: "3.7"
services:
  rover:
    image: aztfmod/rover:0.15.4-2105.2603
    user: vscode

    labels:
      - "caf=Azure CAF"

    volumes:
      - ..:/tf/caf
      - volume-caf-vscode:/home/vscode
      - volume-caf-vscode-bashhistory:/commandhistory
      - ~/.ssh:/tmp/.ssh-localhost:ro

      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - HISTFILE=/commandhistory/.bash_history
      - HISTSIZE=1000

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  volume-caf-vscode:
    labels:
      - "caf=Azure CAF"
  volume-caf-vscode-bashhistory:
