name: master

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Hub Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: aztfmod 
        # Container registry password
        password: ${{ secrets.docker_registry_password }}
        # Container registry server url
        login-server: https://index.docker.io/v1/
    - name: Build the rover
      run: |
        set -e
        tag=$(date +"%g%m.%d%H")

        # Build the rover base image
        docker-compose build --build-arg versionRover="aztfmod/rover:$tag"

        docker tag rover_rover aztfmod/rover:$tag
        docker push aztfmod/rover:$tag

    - name: Create Release
      if: github.event_name == 'pull_request' 
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false