name: vnext

on:
  pull_request:
    branches:
      - vnext
  push:
    branches:
      - vnext

env:
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_azure_devops_pat_token: ${{ secrets.TF_VAR_azure_devops_pat_token }}
  TF_VAR_azure_devops_url_organization: ${{ secrets.TF_VAR_azure_devops_url_organization }}


jobs:
  build:

    name: Build roverdev
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Hub Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: aztfmod 
        # Container registry password
        password: ${{ secrets.docker_registry_password }}
        # Container registry server url
        login-server: https://index.docker.io/v1/
    - name: Build the rover
      run: |        
        set -e
        docker_tag=$(date +"%g%m.%d%H%M")
        echo ::set-env name=docker_tag::${docker_tag}

        # Build the rover base image
        docker-compose build --build-arg versionRover="aztfmod/roverdev:$docker_tag"

        docker tag rover_rover aztfmod/roverdev:$docker_tag
        docker tag rover_rover aztfmod/roverdev:vnext

        docker push aztfmod/roverdev:$docker_tag
        docker push aztfmod/roverdev:vnext

    - name: Build the rover
      run: |        
        set -e
        docker_tag=vnext-13-beta1
        
        # Override .env variable
        export versionTerraform="0.13.0-beta1"

        # Build the rover base image
        docker-compose build --build-arg versionRover="aztfmod/roverdev:$docker_tag"

        docker tag rover_rover aztfmod/roverdev:$docker_tag

        docker push aztfmod/roverdev:$docker_tag

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.docker_tag }}
        release_name: aztfmod/roverdev:${{ env.docker_tag }}
        draft: true
        prerelease: false
        body: You can also use the latest vnext by using aztfmod/roverdev:vnext